version: '3'
services:

  nfts-metadata:
    image: iexechub/nfts-metadata:0.0.5
    restart: always
    volumes:
      - ./server:/mnt
    environment:
      CONFIG: /mnt/config.json


  nginx:
    image: nginx
    restart: always
    ports:
      - '443:443'
    depends_on:
      - nfts-metadata
    volumes:
      - ./nginx:/etc/nginx
      - ./assets:/mnt/assets
      - /etc/letsencrypt:/etc/letsencrypt
